-- ============================================================
-- Migration 001: PRISM core schema
--
-- Money is INTEGER MINOR UNITS (paise) everywhere. Never NUMERIC,
-- never a float: the amount is hashed into the intent, and a value
-- that can be formatted two ways can be hashed two ways.
--
-- Migrations are append-only after this one has been applied.
-- Need a change? Add 002_*.sql. Do not edit this file.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE transaction_status AS ENUM (
  'PENDING',           -- intent locked, awaiting authorization
  'STEP_UP_REQUIRED',  -- risk engine asked for semantic verification
  'AUTHORIZED',        -- all checks passed, not yet settled
  'SETTLED',           -- money moved, exactly once
  'BLOCKED',           -- refused; see failure_code
  'EXPIRED'            -- intent window closed
);

CREATE TYPE ledger_direction AS ENUM ('DEBIT', 'CREDIT');

-- ============================================================
-- Users
-- ============================================================

CREATE TABLE users (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  email        TEXT        NOT NULL UNIQUE,
  display_name TEXT        NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- Accounts — where the money actually lives.
-- An external account (is_external) has no user and models a payee
-- outside PRISM, so the demo can pay a stranger without inventing one.
-- ============================================================

CREATE TABLE accounts (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID        REFERENCES users(id) ON DELETE CASCADE,
  display_name  TEXT        NOT NULL,
  handle        TEXT        NOT NULL UNIQUE,          -- e.g. priya@prism
  balance_minor BIGINT      NOT NULL DEFAULT 0 CHECK (balance_minor >= 0),
  is_external   BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_accounts_user_id ON accounts(user_id);

-- ============================================================
-- WebAuthn credentials — device-bound, one row per passkey.
-- The private key never reaches us; we store only the public key.
-- ============================================================

CREATE TABLE credentials (
  id           TEXT        PRIMARY KEY,              -- credential ID, base64url
  user_id      UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  public_key   BYTEA       NOT NULL,
  counter      BIGINT      NOT NULL DEFAULT 0,       -- stored, NOT trusted: many
                                                     -- platform authenticators
                                                     -- always return 0
  device_type  TEXT        NOT NULL DEFAULT 'singleDevice',
  backed_up    BOOLEAN     NOT NULL DEFAULT FALSE,
  transports   TEXT[],
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ,
  revoked_at   TIMESTAMPTZ                           -- stolen-device revocation
);

CREATE INDEX idx_credentials_user_id ON credentials(user_id);

-- ============================================================
-- Transactions — the locked intent.
-- Nothing in the hashed set may ever be UPDATEd: changing an amount
-- means creating a new transaction with a new id, nonce and hash.
-- ============================================================

CREATE TABLE transactions (
  id                UUID               PRIMARY KEY DEFAULT gen_random_uuid(),
  payer_user_id     UUID               NOT NULL REFERENCES users(id),
  payer_account_id  UUID               NOT NULL REFERENCES accounts(id),
  payee_account_id  UUID               NOT NULL REFERENCES accounts(id),
  amount_minor      BIGINT             NOT NULL CHECK (amount_minor > 0),
  currency          TEXT               NOT NULL DEFAULT 'INR',
  intent_hash       TEXT               NOT NULL UNIQUE,  -- base64url; IS the
                                                         -- WebAuthn challenge
  nonce             TEXT               NOT NULL UNIQUE,
  lock_version      INTEGER            NOT NULL DEFAULT 1,
  created_at        TIMESTAMPTZ        NOT NULL DEFAULT NOW(),
  expires_at        TIMESTAMPTZ        NOT NULL,
  status            transaction_status NOT NULL DEFAULT 'PENDING',
  risk_score        INTEGER,
  risk_reasons      JSONB              NOT NULL DEFAULT '[]',
  failure_code      TEXT,
  settled_at        TIMESTAMPTZ,
  CONSTRAINT no_self_payment CHECK (payer_account_id <> payee_account_id)
);

CREATE INDEX idx_transactions_payer   ON transactions(payer_user_id, created_at DESC);
CREATE INDEX idx_transactions_status  ON transactions(status);
CREATE INDEX idx_transactions_payee   ON transactions(payer_user_id, payee_account_id);

-- ============================================================
-- Ledger — double-entry, and the third independent replay defence.
--
-- The UNIQUE constraint on transaction_id + direction means a transaction
-- can post its DEBIT and CREDIT exactly once, ever. This is enforced by
-- the database, not by application code: even a perfectly forged approval
-- arriving twice concurrently cannot settle twice.
-- ============================================================

CREATE TABLE ledger_entries (
  id             UUID             PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_id UUID             NOT NULL REFERENCES transactions(id),
  account_id     UUID             NOT NULL REFERENCES accounts(id),
  direction      ledger_direction NOT NULL,
  amount_minor   BIGINT           NOT NULL CHECK (amount_minor > 0),
  settled_at     TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  UNIQUE (transaction_id, direction)
);

CREATE INDEX idx_ledger_account ON ledger_entries(account_id, settled_at DESC);

-- ============================================================
-- Audit — append-only. Every decision writes one row.
-- No UPDATE or DELETE is ever issued against this table; that is a
-- discipline, not a database grant, and the README says so plainly.
-- ============================================================

CREATE TABLE audit_logs (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_id UUID        REFERENCES transactions(id),
  user_id        UUID        REFERENCES users(id),
  event_type     TEXT        NOT NULL,
  event_data     JSONB       NOT NULL DEFAULT '{}',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_transaction ON audit_logs(transaction_id, created_at);
CREATE INDEX idx_audit_event_type  ON audit_logs(event_type, created_at DESC);
